apiVersion: v1 
kind: Pod
metadata:
  name: pod-config
  labels:
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "120m"
        memory: "128Mi"
    #configmap
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: course
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: duration
