apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    project: expense
    module: backend
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
  template:
    metadata:
      labels:
        project: expense
    spec:
      containers:
      - name: nginx
        # image: nginx # version-1
        image: nginx:stable-perl # version -2 image upgraded


---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-deployment
spec:
  type: ClusterIP
  selector:
    project: expense
  ports:
  - name: nginx-svc-port
    protocol: "TCP"
    port: 80
    targetPort: 80