apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    project: expense
    module: backend
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
  template:
    metadata:
      labels:
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx